name: student_expense_tracker
description: A simple Flutter app to track student expenses and small loans.

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.6
  flutter_launcher_icons: ^0.13.1
flutter:
  uses-material-design: true
flutter_launcher_icons:
  android: "launcher_icon" # Filename of your Android icon (e.g., launcher_icon.png)
  ios: true
  image_path: "assets/icons/icon_image.png"
